### ISSUE TITLE
Support dio_http_cache plugin

### ISSUE THREAD

**Issue by Reprevise** [dart-tools/dio_http#1]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/dart-tools/dio_http/issues) and found none

### Issue Description and Steps

Please provide official `dio_http_cache` plugin support.

**Comment by jgoyvaerts** [comment]
Dio_http_cache is a separate library by someone else, if you want them to switch to our fork of dio you can make an issue/PR on their repo: https://github.com/hurshi/dio-http-cache
