### ISSUE TITLE
Why throw sendTimeout error with the param 'connectTimeout'

### ISSUE THREAD

**Issue by mingchaogui** [dart-tools/dio_http#15]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/dart-tools/dio_http/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter                          |      |
| Platform Version               | 2.2.3                              |      |
| Dio Version                    | 5.0.4                                  |      |
| Android Studio / Xcode Version |  Android Studio 2020.3.1 Patch 3              |      |
| Repro rate                     | all the time   |      |
| Repro with our demo prj        | It does            |      |
| Demo project link              | NONE |      |

### Issue Description and Steps

dio_mixin.dart
```
      if (options.sendTimeout > 0) {
        byteStream.timeout(Duration(milliseconds: options.sendTimeout),
            onTimeout: (sink) {
          sink.addError(DioError(
            requestOptions: options,
            error: 'Sending timeout[${options.connectTimeout}ms]',
            type: DioErrorType.sendTimeout,
          ));
          sink.close();
        });
      }
```

And DioErrorType.connectTimeout has never been used.

**Comment by jgoyvaerts** [comment]
This package is now archived. This was originally forked because the owner of the [Dio](https://github.com/flutterchina/dio) package was inactive, but he has sinced returned from inactiveness and has added some more contributors to prevent this from happening again in the future. All future development continues over on [Dio](https://github.com/flutterchina/dio).
