### ISSUE TITLE
Readme plugin pub links in wrong order

### ISSUE THREAD

**Issue by Jaakkonen** [dart-tools/dio_http#8]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/dart-tools/dio_http/issues) and found none

### Issue Info
dio_cookie_manager -> https://pub.dartlang.org/packages/dio_http2_adapter
dio_http2_adapter -> https://pub.dartlang.org/packages/dio_cookie_manager

**Comment by jgoyvaerts** [comment]
Fixed, thanks for the report!
